// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.DAL.Context;

#nullable disable

namespace TaxCalculator.DAL.Migrations
{
    [DbContext(typeof(TaxCalculatorDbContext))]
    partial class TaxCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCalculator.DbModels.TaxBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LowerBound")
                        .HasColumnType("int");

                    b.Property<int>("RateInPercents")
                        .HasColumnType("int");

                    b.Property<int>("UpperBound")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxBands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7474843-f83c-432a-920b-3149e32a8847"),
                            LowerBound = 0,
                            RateInPercents = 0,
                            UpperBound = 5000
                        },
                        new
                        {
                            Id = new Guid("d0606ca2-2337-436c-80e9-ced465be3a8c"),
                            LowerBound = 5000,
                            RateInPercents = 20,
                            UpperBound = 20000
                        },
                        new
                        {
                            Id = new Guid("d71f3efe-f490-4fdd-8bbb-83c319654874"),
                            LowerBound = 20000,
                            RateInPercents = 40,
                            UpperBound = 2147483647
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
